#%RAML 1.0 Library

usage: Space types specifics

uses:
  product: product.raml
  base: ../../public/types/base.raml

types:
  Space:
    type: base.Base
    properties:
      author_id: string

  FittingRoom:
    type: base.Content
    properties:
      items: nil | product.Product[]
