#%RAML 1.0
title: Galaxy-solar gstar Backend API
version: v1
baseUri: http://localhost/{version}/
mediaType: application/json

uses:
  meta: ./types/meta.raml
  space: ./types/space.raml
  trait: ../public/traits/traits.raml
  sku: ./types/sku.raml
  device: ./types/device.raml

resourceTypes:
  collection: !include ../public/resourceTypes/collection.raml
  item: !include ../public/resourceTypes/item.raml

/spaces:
  displayName: specific space type management
  type:
    collection:
      request-type: space.Space
      response-type: space.Space
      exampleCollection: !include ./examples/space_collection_simple.get.example
      exampleItem: !include ./examples/space_item.post.example
  get:
    queryParameters:
      space_type?:
        type: string
        description: filter for space.type
    description: 获取对应类型所有的space，比如试衣间
    is: [ trait.pageable, trait.sortable, trait.partial, trait.filterable ]
  post:
    description: 添加一个试衣间（或根据type区分是什么类型的space）
  /{space_id}:
    uriParameters:
      space_id: string
    type:
      item:
        request-type: space.Space
        response-type: space.Space
        exampleItem: !include ./examples/space_item.get.example
        exampleItemPut: !include ./examples/space_item.post.example
        exampleItemDelete: !include ./examples/space_item.post.example
    get:
      description: 获取试衣间详情（返回数据包括已送入试衣间的单品图片）
    put:
      description: backend update; RFID scan
    delete:
    /skus:
      type:
        collection:
          response-type: object
          exampleCollection: !include ./examples/space_dressing_sku.get.example
          request-type: string
          exampleItem: json
      get:
        description: 获取指定试衣间里所有的单品信息（包括单品其他尺码、颜色等数据）
      post:
        description: 用户指定换送衣服接口


/devices:
  type:
     collection:
       response-type: device.Device
       exampleCollection: !include ./examples/space_device.get.example
       request-type: device.Device
       exampleItem: !include ./examples/space_device.post.example
  get:
    queryParameters:
      device_type?: string
  post:
  delete:
