#%RAML 1.0
title: Galaxy-solar store Client API
version: v1
baseUri: http://localhost/{version}/
mediaType: application/json

uses:
  meta: ./types/meta.raml
  space: ./types/space.raml
  trait: ../public/traits/traits.raml

resourceTypes:
  collection: !include ../public/resourceTypes/collection.raml
  item: !include ../public/resourceTypes/item.raml

/spaces:
  displayName: space client
  /{space_type}:
    displayName: specific space type management
    uriParameters:
      space_type:
        type: string
        description: filter for space.type
    type:
      collection:
        request-type: space.Space
        response-type: space.Space
        exampleCollection: !include ./examples/space_collection_simple.get.example
        exampleItem: !include ./examples/space_item.post.example
    get:
      is: [ trait.pageable, trait.sortable, trait.partial, trait.filterable ]
  /{space_id}:
    uriParameters:
      space_id: string
    type:
      item:
        request-type: space.Space
        response-type: space.Space
        exampleItem: !include ./examples/space_item_simple.get.example
    get:
    /transfer:
      displayName: call a waiter to serve the customer in the fittingroom
      post:
        body:
          application/json:
            type: object
            properties:
              sku_ids:
                type: string[]
                description: sku identifier list
        responses:
          200:
            body:
              application/json:
                example: |
                  { "message": "we have notify the waitresses, please wait" }
